### ISSUE TITLE
GetUserTimeline not working anymore.

### ISSUE THREAD

**Issue by karlcow** [olivierthereaux/oldtweets#5]
I'm not sure what is wrong yet. But it seems there is an issue.

```
→ cat credentials.txt | ./oldtweets.py --dry-run

Traceback (most recent call last):
  File "./oldtweets.py", line 138, in <module>
    sys.exit(main())
  File "./oldtweets.py", line 103, in main
    add_statuses = api.GetUserTimeline(count=200, include_rts=True,    page=timeline_page)
TypeError: GetUserTimeline() got an unexpected keyword argument 'page'
```

**Comment by olivierthereaux** [comment]
Works now with most recent version of python-twitter.
